[package]
name = "disasm"
version = "0.2.0"
authors = ["Tomas Koutsky <tomas@stepnivlk.net>"]
edition = "2018"

[dependencies]
clap = {version = "2.32", features = ["yaml"]}
serde = "1.0.85"
serde_derive = "1.0.85"
serde_json = "1.0.36"
